### ISSUE TITLE
Unresolved reference: "WhatsAppUserUiState".

### ISSUE THREAD

**Issue by Ahmad-Hamwi** [GetStream/whatsApp-clone-compose#4]
The class at "io.getstream.whatsappclone.uistate.WhatsAppUserUiState" is missing. 

Opened the module "core-uistate" and I haven't found the file WhatsAppUserUiState.kt

Am I missing something here?

**Comment by skydoves** [comment]
Hi @Ahmad-Hamwi, `WhatsAppUserUiState` is a generated class after compiling the project.
The `UiState` in this project generates dedicated Ui models based on [SealedX](https://github.com/skydoves/sealedx) Kotlin Symbol Processing. You can find more information about the [Kotlin Symbol Processing](https://kotlinlang.org/docs/ksp-overview.html).

**Comment by Ahmad-Hamwi** [comment]
@skydoves Thank you for your quick response and explanation. I'm reading more about SealedX and KSP and they rock!
